spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: lorrycircle123
