server:
  port: 9099
management:
  endpoint:
    info:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localdb:3306/ast_db?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: ast123
