server:
  port: 9099
management:
  endpoint:
    info:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://lorry-circle-dev.cgiqfxwnfwyk.ap-south-1.rds.amazonaws.com:3306/ez_lorry_db_alpha?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: hegde123
