server:
  port: 4001
management:
  endpoint:
    info:
      enabled: true
lc:
  auth:
    key: q3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeTh
    defaultExpiry: 300
    clients:
      - name: rfq-service
        secret: rfq
        grantTypes:
          - client_credentials
          - refresh_token
        scope: server
      - name: corporate-service
        secret: corporate
        grantTypes:
          - client_credentials
          - refresh_token
        scope: server
      - name: owner-service
        secret: owner
        grantTypes:
          - client_credentials
          - refresh_token
        scope: server
      - name: consumer-service
        secret: consumer
        grantTypes:
          - client_credentials
          - refresh_token
        scope: server
      - name: booking-service
        secret: booking
        grantTypes:
          - client_credentials
          - refresh_token
        scope: server
      - name: document-service
        secret: document
        grantTypes:
         - client_credentials
         - refresh_token
        scope: server
      - name: communication-service
        secret: communication
        grantTypes:
         - client_credentials
         - refresh_token
        scope: server
spring:
  datasource:
    url: jdbc:mysql://lorry-circle-dev.cgiqfxwnfwyk.ap-south-1.rds.amazonaws.com:3306/ez_lc_nxgen?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: hegde123
api:
  version: 1.0-beta
