spring:
  datasource:
    url: jdbc:mysql://162.246.249.141:3306/ez_lc_nxgen?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: ez_lc_nxgen_usr
    password: OF7l2r!2j5JbWz(g
feign:
  url:
    plainUrl: https://dbqa-api.lorrycircle.com/api/
    auth: https://dbqa-api.lorrycircle.com/api/auth
    audit: https://dbqa-api.lorrycircle.com/api/audit
    communication: https://dbqa-api.lorrycircle.com/api/communication
    booking: https://dbqa-api.lorrycircle.com/api/booking
    lookup: https://dbqa-api.lorrycircle.com/api/lookup
lc:
  sync:
    url: https://2iprkna5mrf3hczfldtz4tuibq.appsync-api.ap-south-1.amazonaws.com
    keyId: da2-lktpf6fbjzfxzemlomsgn32brq
  email:
    defaultSender: no-reply@lorrycircle.com
  sms:
    url: http://sms.slvtechnologies.in/REST/sendsms
    username: LORRYC
    password: 6842789a7bXX
    senderId: LORRYC
    accountusagetypeid: 1
    entityid: 1701159230492420071
  notification:
    url: https://fcm.googleapis.com/fcm/send
    key: AAAAQKx3ZhA:APA91bF0Rv5ZxRZCNOVRwZKc0mRhdJBijw9pVWJKAh05JgFkwEzF8YGxRcshbMGzHBJlCjX0N7tnUYBYHsc3sqSVMt1KvkE-ryD_x0iP1tkaNb7eMjvuQdrYWI1FB3OltcrA_3Ht0Jt1