
spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: lorrycircle123
security:
  oauth2:
    client:
      clientId: communication-service
      clientSecrete: communication
      accessTokenUri: ${ACCESS_TOKEN_URI}
      grant_type: client_credentials
      scope: server
feign:
  url:
    auth: ${BASE_URL}/auth
    lookup: ${BASE_URL}/lookup
    booking: ${BASE_URL}/booking
lc:
  email:
    defaultSender: no-reply@lorrycircle.com
  sms:
    url: http://sms.slvtechnologies.in/REST/sendsms
    username: LORRYC
    password: 6842789a7bXX
    senderId: LORRYC
    accountusagetypeid: 1
    entityid: 1701159230492420071
  notification:
    url: https://fcm.googleapis.com/fcm/send
    key: AIzaSyC9oEJqDOpINByAI42ZL7XAHPzWmM-XCwI
  sync:
    url: https://2iprkna5mrf3hczfldtz4tuibq.appsync-api.ap-south-1.amazonaws.com
    keyId: da2-lktpf6fbjzfxzemlomsgn32brq
