spring:
  datasource:
    url: jdbc:mysql://192.168.1.115:3306/ast_db?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: ast-admin
    password: ta@AST2023
feign:
  url:
    plainUrl: http://gateway:8080/dev
    auth: http://gateway:8080/dev/auth
    audit: http://gateway:8080/dev/audit
    communication: http://gateway:8080/dev/communication
    booking: http://localhost:8080/dev/booking
    lookup: http://localhost:8080/dev/lookup