server:
  port: 4002
management:
  endpoint:
    info:
      enabled: true
api:
  version: 1.0-beta
security:
  oauth2:
    client:
      clientId: communication-service
      clientSecrete: communication
      accessTokenUri: http://gateway:8080/auth/oauth/token/
      grant_type: client_credentials
      scope: server
spring:
  datasource:
    url: jdbc:mysql://localdb:3306/ast_db?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: ast123
feign:
  url:
    plainUrl: http://gateway:8080/dev
    auth: http://gateway:8080/dev/auth
    audit: http://gateway:8080/dev/audit
    communication: http://gateway:8080/dev/communication
    booking: http://localhost:8080/dev/booking
    lookup: http://localhost:8080/dev/lookup