spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ez_lc_nxgen?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: lc123
security:
  oauth2:
    client:
      clientId: consumer-service
      clientSecrete: consumer
      accessTokenUri: http://localhost:4001/auth/oauth/token/
      grant_type: client_credentials
      scope: server