server:
  port: 9002
management:
  endpoint:
    info:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ez_lc_nxgen?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: root
    password: lc123
api:
  version: 1.0-beta
security:
  oauth2:
    client:
      clientId: corporate-service
      clientSecrete: corporate
      accessTokenUri: http://localhost/auth/oauth/token/
      grant_type: client_credentials
      scope: server