management:
  endpoint:
    info:
      enabled: true
server:
  port: 81
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*" 
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/dev/auth/**
          filters:
            - RewritePath=/dev/auth/(?<path>.*), /$\{path}
        - id: audit
          uri: lb://audit-service
          predicates:
            - Path=/dev/audit/**
          filters:
            - RewritePath=/dev/audit/(?<path>.*), /$\{path}
        - id: corporate
          uri: lb://corporate-service
          predicates:
            - Path=/corporate/**
          filters:
            - RewritePath=/corporate/(?<path>.*), /$\{path}
        - id: owner
          uri: lb://owner-service
          predicates:
            - Path=/owner/**
          filters:
            - RewritePath=/owner/(?<path>.*), /$\{path}
        - id: consumer
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer/(?<path>.*), /$\{path}
        - id: booking
          uri: lb://booking-service
          predicates:
            - Path=/dev/booking/**
          filters:
            - RewritePath=/dev/booking/(?<path>.*), /$\{path}
        - id: lookup
          uri: lb://lookup-service
          predicates:
            - Path=/dev/lookup/**
          filters:
            - RewritePath=/dev/lookup/(?<path>.*), /$\{path}
        - id: document
          uri: lb://document-service
          predicates:
            - Path=/dev/document/**
          filters:
            - RewritePath=/dev/document/(?<path>.*), /$\{path}
        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/dev/payment/**
          filters:
            - RewritePath=/dev/payment/(?<path>.*), /$\{path}
        - id: communication
          uri: lb://communication-service
          predicates:
            - Path=/dev/communication/**
          filters:
            - RewritePath=/dev/communication/(?<path>.*), /$\{path}
        - id: report
          uri: lb://report-service
          predicates:
            - Path=/dev/report/**
          filters:
            - RewritePath=/dev/report/(?<path>.*), /$\{path}
