spring:
  datasource:
    url: jdbc:mysql://162.246.249.141:3306/ez_lc_nxgen?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_general_ci&characterSetResults=utf8
    username: ez_lc_nxgen_usr
    password: OF7l2r!2j5JbWz(g
feign:
  url: https://dbqa-api.lorrycircle.com/api/auth
  plainUrl: https://dbqa-api.lorrycircle.com/api
  audit: https://dbqa-api.lorrycircle.com/api/audit
  communication: https://dbqa-api.lorrycircle.com/api/communication
redirect:
  url: http://localhost:4200/customer/my-quotes
  plainUrl: http://localhost:4200